version: '3'
services:
  web:
    image: react
    build: ./react
    container_name: react
    restart: always
    # we can see the server running at "localhost:3000"
    ports:
      - "3000:3000"

  e2e:
    image: cypress-docker
    build: ./e2e
    container_name: cypress-docker
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json